# Config file for automatic testing at travis-ci.org

sudo: false
language: python
cache: pip

matrix:
    include:
      - python: 2.6
        env: TOX_ENV=py26
      - python: 2.7
        env: TOX_ENV=py27
      - python: 3.3
        env: TOX_ENV=py33
      - python: 3.4
        env: TOX_ENV=py34
      - python: 3.5
        env: TOX_ENV=py35
      - python: pypy
        env: TOX_ENV=pypy
      - python: 3.5
        env: TOX_ENV=py35
      - python: nightly
        env: TOX_ENV=py36

script: tox -e $TOX_ENV

install:
    - pip install tox coverage


after_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - coverage combine
    - pip install codecov
    - codecov -e TOX_ENV TRAVIS_OS_NAME
